package tr.ets2nav.map;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Builds the MapLibre style JSON for the game tiles (vector layer "ets2" /
 * "ats", generated by truckermudgeon's `generator map`). Adapted from
 * packages/libs/ui/GameMapStyle.tsx, with Google-Maps-like colors and only the
 * layers a 1 GB / GLES2 head unit can afford (no footprints/extrusions).
 */
public final class MapStyle {
  public static final String LAYER_ROUTE_ANCHOR = "labels-anchor";

  private MapStyle() {}

  private static final class Palette {
    String background, water, roadArea, lightArea, darkArea, greenArea, prefabRoad;
    String freeway, freewayCase, divided, dividedCase, local, localCase, noVehicles, noVehiclesCase;
    String ferry, text, textHalo, secondaryText;
  }

  private static Palette light() {
    Palette p = new Palette();
    p.background = "#ebe9e4";
    p.water = "#a8c8f0";
    p.roadArea = "#e2e4e7";
    p.lightArea = "#f0e6d2";
    p.darkArea = "#e4cfa6";
    p.greenArea = "#c9e4c1";
    p.prefabRoad = "#ffffff";
    p.freeway = "#fde293";
    p.freewayCase = "#e8b440";
    // Same as freeway: many DLC motorways are "divided" in the game data, and
    // two colors made one highway look striped.
    p.divided = "#fde293";
    p.dividedCase = "#e8b440";
    p.local = "#ffffff";
    p.localCase = "#d3d5d9";
    p.noVehicles = "#d8d8d8";
    p.noVehiclesCase = "#bdbdbd";
    p.ferry = "#5b8fd6";
    p.text = "#3c4043";
    p.textHalo = "#ffffff";
    p.secondaryText = "#5f6368";
    return p;
  }

  private static Palette dark() {
    Palette p = new Palette();
    p.background = "#1f2733";
    p.water = "#17263c";
    p.roadArea = "#2d3643";
    p.lightArea = "#2e3440";
    p.darkArea = "#39414d";
    p.greenArea = "#23372e";
    p.prefabRoad = "#3d4654";
    p.freeway = "#8a7a4e";
    p.freewayCase = "#2a2a22";
    p.divided = "#8a7a4e";
    p.dividedCase = "#2a2a22";
    p.local = "#3d4654";
    p.localCase = "#1b222c";
    p.noVehicles = "#343b46";
    p.noVehiclesCase = "#1b222c";
    p.ferry = "#6f9ddb";
    p.text = "#d6d9de";
    p.textHalo = "#101419";
    p.secondaryText = "#9aa0a6";
    return p;
  }

  /**
   * @param game       "ets2" or "ats" (also the vector layer name)
   * @param tileUrl    XYZ template served by LocalTileServer
   * @param spriteUrl  the POI icon sheet (downloaded from the PC), or null: no icons yet
   */
  public static String build(String game, String tileUrl, String spriteUrl, boolean darkMode) {
    Palette c = darkMode ? dark() : light();
    try {
      JSONObject style = new JSONObject();
      style.put("version", 8);
      style.put("name", "ets2nav-" + (darkMode ? "dark" : "light"));
      style.put("glyphs", "asset://glyphs/{fontstack}/{range}.pbf");
      if (spriteUrl != null) style.put("sprite", spriteUrl);

      JSONObject src = new JSONObject()
          .put("type", "vector")
          .put("tiles", new JSONArray().put(tileUrl))
          .put("minzoom", 4)
          .put("maxzoom", 13);
      style.put("sources", new JSONObject().put("game", src));

      JSONArray layers = new JSONArray();
      layers.put(new JSONObject().put("id", "background").put("type", "background")
          .put("paint", new JSONObject().put("background-color", c.background)));

      // city/company/scenery areas
      layers.put(layer("map-areas", "fill", game)
          .put("filter", all(geom("Polygon"), eq("type", "mapArea")))
          .put("paint", new JSONObject().put("fill-color", areaColor(c, false)).put("fill-antialias", false)));
      // junction/prefab road surfaces
      layers.put(layer("prefabs", "fill", game)
          .put("filter", all(geom("Polygon"), eq("type", "prefab")))
          .put("paint", new JSONObject().put("fill-color", areaColor(c, true)).put("fill-antialias", false)));

      JSONArray roadFilter = all(geom("LineString"), eq("type", "road"), eq("hidden", false),
          new JSONArray().put("!=").put(get("roadType")).put("train"));
      JSONObject roadLayout = new JSONObject().put("line-cap", "round").put("line-join", "round");
      layers.put(layer("roads-case", "line", game).put("minzoom", 5)
          .put("filter", roadFilter)
          .put("layout", roadLayout)
          .put("paint", new JSONObject()
              .put("line-color", roadColor(c, true))
              .put("line-gap-width", roadWidth())
              .put("line-width", interpolate(5, 0.6, 10, 0.8, 13, 1.5, 16, 3))));
      layers.put(layer("roads", "line", game)
          .put("filter", roadFilter)
          .put("layout", roadLayout)
          .put("paint", new JSONObject()
              .put("line-color", roadColor(c, false))
              .put("line-width", roadWidth())));
      layers.put(layer("ferries", "line", game)
          .put("filter", all(geom("LineString"), eq("type", "ferry")))
          .put("paint", new JSONObject().put("line-color", c.ferry).put("line-width", 1.5)
              .put("line-dasharray", new JSONArray().put(2).put(2))));

      // Route/truck layers are inserted below this marker (see NavMapController).
      layers.put(new JSONObject().put("id", LAYER_ROUTE_ANCHOR).put("type", "background")
          .put("layout", new JSONObject().put("visibility", "none"))
          .put("paint", new JSONObject().put("background-color", c.background)));

      layers.put(layer("poi-icons", "symbol", game).put("minzoom", 10.5)
          .put("filter", all(geom("Point"), eq("type", "poi"), eq("poiType", "facility"),
              new JSONArray().put("in").put(get("sprite")).put(new JSONArray().put("literal")
                  .put(new JSONArray().put("gas_ico").put("service_ico").put("parking_ico")
                      .put("dealer_ico").put("garage_large_ico").put("recruitment_ico")
                      .put("weigh_station_ico")))))
          .put("layout", new JSONObject()
              .put("icon-image", "{sprite}")
              .put("icon-size", interpolate(10.5, 0.85, 13, 1.2, 16, 1.7))
              .put("icon-padding", 4)));
      layers.put(layer("road-facility-icons", "symbol", game).put("minzoom", 11)
          .put("filter", all(geom("Point"), eq("type", "poi"), eq("poiType", "road"),
              new JSONArray().put("in").put(get("sprite")).put(new JSONArray().put("literal")
                  .put(new JSONArray().put("toll_ico").put("border_ico").put("weigh_ico")))))
          .put("layout", new JSONObject()
              .put("icon-image", "{sprite}")
              .put("icon-size", interpolate(11, 0.8, 14, 1.2))));

      JSONObject textPaint = new JSONObject()
          .put("text-color", c.text).put("text-halo-color", c.textHalo).put("text-halo-width", 1.6);
      layers.put(cityLabels("city-small", game, 7.5, 13, all(geom("Point"), eq("type", "city"),
          new JSONArray().put(">").put(get("scaleRank")).put(6)), 13, false, textPaint));
      layers.put(cityLabels("city-medium", game, 6, 12, all(geom("Point"), eq("type", "city"),
          new JSONArray().put("<=").put(get("scaleRank")).put(6),
          new JSONArray().put(">").put(get("scaleRank")).put(3)), 14, false, textPaint));
      layers.put(cityLabels("city-big", game, 4, 11, all(geom("Point"), eq("type", "city"),
          new JSONArray().put("<=").put(get("scaleRank")).put(3)), 16, true, textPaint));
      layers.put(layer("country-labels", "symbol", game).put("minzoom", 4).put("maxzoom", 7)
          .put("filter", all(geom("Point"), eq("type", "country")))
          .put("layout", new JSONObject()
              .put("text-field", "{name}")
              .put("text-font", new JSONArray().put("Klokantech Noto Sans Bold"))
              .put("text-size", 14)
              .put("text-transform", "uppercase"))
          .put("paint", new JSONObject().put("text-color", c.secondaryText)
              .put("text-halo-color", c.textHalo).put("text-halo-width", 1.2)));

      style.put("layers", layers);
      return style.toString();
    } catch (JSONException e) {
      throw new IllegalStateException(e);
    }
  }

  private static JSONObject cityLabels(String id, String game, double minZoom, double maxZoom,
                                       JSONArray filter, int size, boolean bold, JSONObject paint)
      throws JSONException {
    return layer(id, "symbol", game).put("minzoom", minZoom).put("maxzoom", maxZoom)
        .put("filter", filter)
        .put("layout", new JSONObject()
            .put("text-field", "{name}")
            .put("text-font", new JSONArray().put(bold ? "Klokantech Noto Sans Bold" : "Klokantech Noto Sans Regular"))
            .put("text-size", size)
            .put("text-padding", 6))
        .put("paint", paint);
  }

  private static JSONObject layer(String id, String type, String sourceLayer) throws JSONException {
    return new JSONObject().put("id", id).put("type", type).put("source", "game").put("source-layer", sourceLayer);
  }

  private static JSONArray get(String prop) {
    return new JSONArray().put("get").put(prop);
  }

  private static JSONArray eq(String prop, Object value) {
    return new JSONArray().put("==").put(get(prop)).put(value);
  }

  private static JSONArray geom(String type) {
    return new JSONArray().put("==").put(new JSONArray().put("geometry-type")).put(type);
  }

  private static JSONArray all(JSONArray... conds) {
    JSONArray a = new JSONArray().put("all");
    for (JSONArray c : conds) a.put(c);
    return a;
  }

  private static JSONArray interpolate(double... stops) {
    try {
      JSONArray a = new JSONArray().put("interpolate")
          .put(new JSONArray().put("exponential").put(1.5)).put(new JSONArray().put("zoom"));
      for (double s : stops) a.put(s);
      return a;
    } catch (JSONException e) {
      throw new IllegalStateException(e);
    }
  }

  // Map units are ~19x game meters, so a lane is wide on screen at zoom 13+.
  private static JSONArray roadWidth() {
    return interpolate(5, 1.2, 8, 1.8, 10, 2.4, 12, 4.8, 13, 9, 14, 18, 16, 72);
  }

  private static JSONArray roadColor(Palette c, boolean casing) {
    return new JSONArray().put("match").put(get("roadType"))
        .put("freeway").put(casing ? c.freewayCase : c.freeway)
        .put("divided").put(casing ? c.dividedCase : c.divided)
        .put("local").put(casing ? c.localCase : c.local)
        .put("no_vehicles").put(casing ? c.noVehiclesCase : c.noVehicles)
        .put(casing ? c.localCase : c.local);
  }

  // MapAreaColor: 0 road, 1 light, 2 dark, 3 green, 4-8 nav colors
  private static JSONArray areaColor(Palette c, boolean prefab) {
    return new JSONArray().put("match").put(get("color"))
        .put(0).put(prefab ? c.prefabRoad : c.roadArea)
        .put(1).put(c.lightArea)
        .put(2).put(c.darkArea)
        .put(3).put(c.greenArea)
        .put(4).put("#b33a3a")
        .put(5).put("#4f9a3c")
        .put(6).put("#3a7ab0")
        .put(7).put("#d9c23a")
        .put(8).put("#7a4fb0")
        .put(c.roadArea);
  }
}
